packages:
  - apps/*
  - packages/*

allowBuilds:
  browser-tabs-lock: false
  core-js: false
  workerd: false

catalog:
  effect: 4.0.1
  "@effect/atom-react": 4.0.1
  "@effect/sql-sqlite-do": 4.0.1
  "@effect/vitest": 4.0.1
  "@effect/platform-node": 4.0.1
  "@clerk/backend": 3.18.1
  "@clerk/expo": 4.6.8
  typescript: 5.9.2
  vite-plus: 1.0.0
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0
  "@types/node": 24.12.4
  "@legendapp/list": 3.3.5
